### ISSUE TITLE
Examples of reductions of structure group and associated bundles

### ISSUE THREAD

**Issue by JeffJiang42** [JeffJiang42/Undergrad-Thesis#13]

**Comment by adebray** [comment]
One fun example of an associated bundle is: given a principal S_n-bundle P -> X, where S_n is the symmetric group on n elements, there's an associated n-fold cover: let S_n act on [n] := {1, ..., n} in the usual way, and take the associated bundle P x_{S_n} [n]. Correspondingly, one can recover P from this bundle. This is a discrete analogue of the correspondence between vector bundles and principal O_n-bundles.
